services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./static/audio:/app/static/audio
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    env_file:
      - .env
    restart: unless-stopped

volumes:
  uploads:
  audio:
